# Generated by Django 5.1.6 on 2025-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_productvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('SILVER', 'SILVER'), ('BLUE', 'BLUE'), ('GREY', 'GREY'), ('WHITE', 'WHITE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.CharField(choices=[('EXTRASMALL', 'XS'), ('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('EXTRALARGE', 'XL')], max_length=100, null=True),
        ),
    ]
