# Generated by Django 5.1.6 on 2025-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_productvariation_variation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
