# Generated by Django 5.1.6 on 2025-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_remove_productvariation_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('variant', 'variant')], max_length=100, null=True),
        ),
    ]
