# Generated by Django 5.1.6 on 2025-02-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_productvariation_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='Store.product'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('variant', 'Variant')], max_length=100, null=True),
        ),
    ]
