# Generated by Django 5.1.6 on 2025-02-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['date_added'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
