# Generated by Django 5.1.6 on 2025-02-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cart_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='Carts',
        ),
    ]
