# Generated by Django 5.1.6 on 2025-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_rename_cart_carts'),
        ('Store', '0006_alter_productvariation_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Store.productvariation'),
        ),
    ]
