# Generated by Django 5.1.6 on 2025-02-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_cartitem_variations'),
        ('Store', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_product', to='Store.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='cartitem_variations', to='Store.productvariation'),
        ),
    ]
