# Generated by Django 5.1.6 on 2025-02-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_cartitem_product_alter_cartitem_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
    ]
